//
//  CocktailData.swift
//  Apple
//

import Foundation

// MARK: - Model

struct Cocktail: Identifiable {
    let id = UUID()
    let name: String
    let type: String
    let ingredients: [String]
    let steps: [String]
}

// MARK: - Database

let cocktailDatabase: [String: [Cocktail]] = [
    "Whiskey+Smoky": [
        Cocktail(name: "Peated Old Fashioned", type: "Stirred Cocktail",
                 ingredients: ["2 oz peated Scotch whisky", "0.5 oz mezcal",
                               "1 tsp demerara syrup", "2 dashes Angostura bitters", "Orange peel"],
                 steps: ["Combine all in a mixing glass with ice",
                         "Stir 30 seconds until chilled",
                         "Strain into rocks glass over a large cube",
                         "Express orange peel over the glass"]),
        Cocktail(name: "Campfire Sour", type: "Shaken Sour",
                 ingredients: ["2 oz smoky bourbon", "0.75 oz lemon juice",
                               "0.5 oz honey syrup", "1 egg white", "2 dashes smoked paprika tincture"],
                 steps: ["Dry shake all ingredients 15 seconds",
                         "Add ice, shake vigorously 10 seconds",
                         "Double strain into a coupe",
                         "Garnish with smoked salt on foam"]),
        Cocktail(name: "Islay Mule", type: "Highball",
                 ingredients: ["1.5 oz Islay Scotch", "0.5 oz Amaro Montenegro",
                               "0.75 oz lime juice", "3 oz ginger beer", "Lime wheel"],
                 steps: ["Build in a copper mug over crushed ice",
                         "Add Scotch, amaro, and lime juice",
                         "Top with ginger beer and stir gently",
                         "Garnish with lime wheel and candied ginger"]),
    ],
    "Whiskey+Fruity": [
        Cocktail(name: "Cherry Smash", type: "Smash",
                 ingredients: ["2 oz bourbon", "6 pitted fresh cherries",
                               "0.75 oz lemon juice", "0.5 oz simple syrup", "3 mint leaves"],
                 steps: ["Muddle cherries and mint in shaker",
                         "Add remaining ingredients and ice",
                         "Shake vigorously 12 seconds",
                         "Double strain over crushed ice, garnish with cherry and mint"]),
        Cocktail(name: "Whiskey Peach Fizz", type: "Fizz",
                 ingredients: ["1.5 oz rye whiskey", "1 oz peach nectar",
                               "0.75 oz lemon juice", "0.25 oz orgeat", "2 oz soda water"],
                 steps: ["Shake whiskey, peach, lemon, orgeat with ice",
                         "Strain into tall glass over ice",
                         "Top with soda water",
                         "Garnish with a peach slice"]),
        Cocktail(name: "Apple Orchard", type: "Collins",
                 ingredients: ["2 oz bourbon", "1.5 oz fresh apple juice",
                               "0.5 oz ginger liqueur", "0.75 oz lemon juice", "1 oz club soda"],
                 steps: ["Shake bourbon, apple, ginger liqueur, lemon",
                         "Strain into Collins glass over ice",
                         "Top with club soda",
                         "Garnish with cinnamon stick"]),
    ],
    "Whiskey+Herbal": [
        Cocktail(name: "Green Boulevardier", type: "Stirred Cocktail",
                 ingredients: ["1.5 oz rye whiskey", "0.75 oz green Chartreuse",
                               "0.75 oz sweet vermouth", "2 dashes orange bitters", "Lemon twist"],
                 steps: ["Combine all in a mixing glass with ice",
                         "Stir 40 rotations until diluted and chilled",
                         "Strain into a chilled coupe",
                         "Express a lemon peel over the surface and discard"]),
        Cocktail(name: "Sage Whiskey Sour", type: "Shaken Sour",
                 ingredients: ["2 oz bourbon", "4 fresh sage leaves",
                               "0.75 oz lemon juice", "0.5 oz honey syrup", "Egg white"],
                 steps: ["Muddle sage with honey syrup in shaker",
                         "Add bourbon, lemon juice, and egg white",
                         "Dry shake 15 seconds, then add ice and shake hard",
                         "Double strain into a coupe, garnish with fried sage"]),
        Cocktail(name: "Highland Fling", type: "Highball",
                 ingredients: ["1.5 oz Scotch", "0.5 oz elderflower liqueur",
                               "0.25 oz Suze", "3 oz tonic water", "Cucumber ribbon"],
                 steps: ["Build in a highball glass over ice",
                         "Add Scotch, elderflower, and Suze",
                         "Top with tonic water",
                         "Stir gently once and garnish with cucumber ribbon"]),
    ],
    "Rum+Fruity": [
        Cocktail(name: "Mango Daiquiri", type: "Shaken Cocktail",
                 ingredients: ["2 oz white rum", "1 oz mango puree",
                               "0.75 oz lime juice", "0.5 oz simple syrup", "Pinch of sea salt"],
                 steps: ["Combine all in shaker with ice",
                         "Shake 12 seconds",
                         "Double strain into chilled coupe",
                         "Garnish with mango fan and lime wheel"]),
        Cocktail(name: "Jungle Bird", type: "Tiki",
                 ingredients: ["1.5 oz aged rum", "0.75 oz Campari",
                               "1.5 oz pineapple juice", "0.5 oz lime juice", "0.5 oz simple syrup"],
                 steps: ["Combine all in shaker with ice",
                         "Shake 10–12 seconds",
                         "Strain over large cube",
                         "Garnish with pineapple frond"]),
        Cocktail(name: "Rum Runner", type: "Tropical",
                 ingredients: ["1 oz dark rum", "1 oz coconut rum", "0.5 oz banana liqueur",
                               "1 oz pineapple juice", "1 oz orange juice", "0.25 oz grenadine"],
                 steps: ["Shake all with ice",
                         "Pour into hurricane glass over crushed ice",
                         "Float a splash of 151 rum",
                         "Garnish with orange slice and cherry flag"]),
    ],
    "Rum+Spicy": [
        Cocktail(name: "Spiced Rum Mule", type: "Highball",
                 ingredients: ["2 oz dark spiced rum", "0.75 oz lime juice",
                               "3 oz ginger beer", "2 jalapeño slices", "Lime wheel"],
                 steps: ["Muddle jalapeño slices in a copper mug",
                         "Fill with crushed ice",
                         "Add rum and lime juice",
                         "Top with ginger beer, stir, garnish with lime and jalapeño"]),
        Cocktail(name: "Devil's Daiquiri", type: "Shaken Cocktail",
                 ingredients: ["2 oz Jamaican rum", "1 seeded habanero pepper",
                               "0.75 oz lime juice", "0.5 oz honey syrup", "Pinch of cayenne"],
                 steps: ["Muddle seeded habanero with honey syrup",
                         "Add rum, lime juice, and cayenne with ice",
                         "Shake hard for 15 seconds",
                         "Double strain into a chilled coupe, garnish with a small chili"]),
        Cocktail(name: "Caribbean Heat", type: "Punch",
                 ingredients: ["1.5 oz coconut rum", "1 oz pineapple juice",
                               "0.5 oz lime juice", "0.5 oz ginger syrup", "2 dashes Tabasco"],
                 steps: ["Build over crushed ice in a rocks glass",
                         "Add rum, pineapple juice, lime juice, ginger syrup, and Tabasco",
                         "Swizzle to combine",
                         "Top with more crushed ice and a mint sprig"]),
    ],
    "Tequila+Fruity": [
        Cocktail(name: "Watermelon Margarita", type: "Margarita",
                 ingredients: ["2 oz blanco tequila", "1.5 oz watermelon juice",
                               "0.75 oz lime juice", "0.5 oz triple sec", "Tajín rim"],
                 steps: ["Rim rocks glass with Tajín",
                         "Shake all with ice",
                         "Strain over fresh ice",
                         "Garnish with a small watermelon wedge"]),
        Cocktail(name: "Tommy's Variation", type: "Margarita",
                 ingredients: ["2 oz reposado tequila", "1 oz lime juice",
                               "0.75 oz agave nectar", "2 oz fresh mango juice"],
                 steps: ["Shake all with ice",
                         "Strain into rocks glass over large cube",
                         "Garnish with lime wheel and mango slice"]),
        Cocktail(name: "Paloma Royale", type: "Sparkling",
                 ingredients: ["1.5 oz tequila", "0.5 oz elderflower liqueur",
                               "0.75 oz grapefruit juice", "2 oz pink grapefruit soda", "Pinch of sea salt"],
                 steps: ["Shake tequila, elderflower, and grapefruit juice with ice",
                         "Strain into highball over ice",
                         "Top with grapefruit soda",
                         "Add a pinch of sea salt and garnish with grapefruit half-wheel"]),
    ],
    "Tequila+Spicy": [
        Cocktail(name: "Picante de la Casa", type: "Spiced Margarita",
                 ingredients: ["2 oz blanco tequila", "1 oz lime juice",
                               "0.75 oz agave nectar", "3 jalapeño slices", "Chili salt rim"],
                 steps: ["Muddle jalapeño in shaker",
                         "Add tequila, lime, agave with ice",
                         "Shake hard 12 seconds",
                         "Double strain into chili-salt rimmed glass, garnish with jalapeño wheel"]),
        Cocktail(name: "Scorpion Negroni", type: "Stirred Cocktail",
                 ingredients: ["1 oz mezcal", "1 oz reposado tequila", "0.75 oz Campari",
                               "0.75 oz sweet vermouth", "2 dashes chipotle bitters"],
                 steps: ["Combine all in mixing glass with ice",
                         "Stir 35 rotations until chilled",
                         "Strain into a rocks glass over a large ice cube",
                         "Garnish with a dehydrated orange wheel"]),
        Cocktail(name: "Desert Storm", type: "Fizz",
                 ingredients: ["1.5 oz añejo tequila", "0.5 oz mezcal", "0.75 oz lime juice",
                               "1 tsp sriracha", "0.5 oz honey syrup", "Ginger beer to top"],
                 steps: ["Shake tequila, mezcal, lime, sriracha, and honey with ice",
                         "Strain into Collins glass over ice",
                         "Top with ginger beer",
                         "Garnish with lime wheel and dried chili"]),
    ],
    "Gin+Herbal": [
        Cocktail(name: "The Botanist's Garden", type: "Stirred",
                 ingredients: ["2 oz London dry gin", "0.5 oz Benedictine",
                               "0.5 oz dry vermouth", "2 dashes celery bitters", "Cucumber ribbon"],
                 steps: ["Combine gin, Benedictine, vermouth, and bitters with ice",
                         "Stir until well diluted",
                         "Strain into a chilled Nick and Nora glass",
                         "Garnish with a long cucumber ribbon"]),
        Cocktail(name: "Basil Gimlet", type: "Shaken Cocktail",
                 ingredients: ["2 oz gin", "8 fresh basil leaves", "0.75 oz lime juice",
                               "0.5 oz simple syrup", "1 oz cucumber juice"],
                 steps: ["Tear and lightly muddle basil in shaker",
                         "Add gin, lime, simple syrup, and cucumber juice with ice",
                         "Shake vigorously 12 seconds",
                         "Double strain into coupe, garnish with basil leaf"]),
        Cocktail(name: "Rosemary & Tonic", type: "Highball",
                 ingredients: ["2 oz gin", "0.25 oz rosemary syrup",
                               "0.5 oz lime juice", "3 oz premium tonic", "Fresh rosemary sprig"],
                 steps: ["Lightly clap the rosemary sprig to release oils",
                         "Build in a balloon glass over a large ice cube",
                         "Add gin, rosemary syrup, and lime juice",
                         "Top with tonic water and garnish with the rosemary sprig"]),
    ],
    "Gin+Floral": [
        Cocktail(name: "Lavender Aviation", type: "Shaken Cocktail",
                 ingredients: ["2 oz gin", "0.5 oz lavender liqueur", "0.5 oz maraschino liqueur",
                               "0.75 oz lemon juice", "Edible lavender flowers"],
                 steps: ["Combine all ingredients in a shaker with ice",
                         "Shake well for 10–12 seconds",
                         "Double strain into a chilled coupe",
                         "Garnish with dried lavender flowers"]),
        Cocktail(name: "Cherry Blossom Fizz", type: "Fizz",
                 ingredients: ["1.5 oz floral gin", "0.5 oz rose syrup", "0.75 oz yuzu juice",
                               "1 egg white", "2 oz elderflower tonic"],
                 steps: ["Dry shake gin, rose syrup, yuzu, and egg white 15 seconds",
                         "Add ice and shake hard 10 more seconds",
                         "Strain into a highball glass over ice",
                         "Top with elderflower tonic and garnish with rose petals"]),
        Cocktail(name: "Garden Party", type: "Collins",
                 ingredients: ["1.5 oz cucumber gin", "0.5 oz violet liqueur",
                               "0.75 oz lemon juice", "0.5 oz honey syrup", "Club soda", "Edible viola"],
                 steps: ["Shake gin, violet, lemon, and honey with ice",
                         "Strain into Collins glass over ice",
                         "Top with club soda",
                         "Float an edible viola on top"]),
    ],
]

// MARK: - Lookup Helper

func getCocktails(spirit: String, flavor: String) -> [Cocktail] {
    let key = "\(spirit)+\(flavor)"
    if let r = cocktailDatabase[key] { return r }
    if let r = cocktailDatabase.first(where: { $0.key.hasPrefix(spirit + "+") })?.value { return r }
    if let r = cocktailDatabase.first(where: { $0.key.hasSuffix("+" + flavor) })?.value { return r }
    return cocktailDatabase["Whiskey+Smokey"]!
}
